### ISSUE TITLE
Can't select first row in ECOs grid

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jumpscale_portal#3]
in the page at '/grid/ECOs'
I can't select the first row of the grid. All other rows works fine.

**Comment by karimal** [comment]
Hey Christophe,
Fixing still in progress for Ecos grid, but just pushed a fix for your problem
https://github.com/Jumpscale/jumpscale_portal/commit/dc32805d393859f8886d201fce2fc362d1c43f3c
